---
applications:
- name: sagan-renderer
  buildpack: java_buildpack
  instances: 2
  health-check-type: http
  health-check-http-endpoint: /health
  memory: 2048M
  disk_quota: 1024M
  routes:
  - route: sagan-renderer.cfapps.io
  services: