---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: gradle
    tag: jdk8
inputs:
- name: sagan-repo
outputs:
- name: build
run:
  user: root
  path: /bin/bash
  args:
  - -c
  - |-
    set -e -u -x
    # sagan-repo will be available with root owner
    # but js things will complain if ran by root
    # so we first change repo owner and then use
    # gradle user to run build
    chown gradle:gradle -R ./sagan-repo
    cd sagan-repo
    su gradle -c "./gradlew --console plain :sagan-renderer:build"
    cd ../
    cp -R sagan-repo/sagan-renderer/build/* build